const ORDER_STATES = {
  RECIBIDA: "RECIBIDA",
  DIAGNOSTICO: "DIAGNOSTICO",
  EN_PROCESO: "EN_PROCESO",
  LISTA: "LISTA",
  ENTREGADA: "ENTREGADA",
  CANCELADA: "CANCELADA",
};

const VALID_TRANSITIONS = {
  RECIBIDA: ["DIAGNOSTICO", "EN_PROCESO", "CANCELADA"],
  DIAGNOSTICO: ["EN_PROCESO", "CANCELADA"],
  EN_PROCESO: ["LISTA", "CANCELADA"],
  LISTA: ["ENTREGADA", "CANCELADA"],
  ENTREGADA: [],
  CANCELADA: [],
};

// Estados a los que un MECANICO puede transicionar
const MECANICO_ALLOWED_TARGETS = ["DIAGNOSTICO", "EN_PROCESO", "LISTA"];

const ITEM_TYPES = ["MANO_OBRA", "REPUESTO"];

module.exports = { ORDER_STATES, VALID_TRANSITIONS, MECANICO_ALLOWED_TARGETS, ITEM_TYPES };
