const ORDER_STATES = {
  RECIBIDA: "RECIBIDA",
  EN_PROCESO: "EN_PROCESO",
  LISTA: "LISTA",
  ENTREGADA: "ENTREGADA",
  CANCELADA: "CANCELADA",
};

const VALID_TRANSITIONS = {
  RECIBIDA: ["EN_PROCESO", "CANCELADA"],
  EN_PROCESO: ["LISTA", "CANCELADA"],
  LISTA: ["ENTREGADA", "CANCELADA"],
  ENTREGADA: [],
  CANCELADA: [],
};

const ITEM_TYPES = ["MANO_OBRA", "REPUESTO"];

module.exports = { ORDER_STATES, VALID_TRANSITIONS, ITEM_TYPES };